export const SITE = {
  name: "It's Not Techy",
  legalName: "It's Not Techy",
  tagline: "Digital marketing that speaks human.",
  description:
    "It's Not Techy is a full-service digital marketing company — web design, SEO, social media, video production, brand design, paid marketing, and marketing platforms — helping ambitious brands grow across the globe.",
  url: "https://itsnottechy.com",
  phone: "+1 672-673-7900",
  phoneRaw: "+16726737900",
  email: "info@itsnottechy.com",
  address: {
    street: "1111 Albion Rd",
    locality: "Etobicoke",
    region: "ON",
    postalCode: "M9V 2X3",
    country: "CA",
    countryName: "Canada",
    full: "1111 Albion Rd, Etobicoke, ON M9V 2X3, Canada",
  },
  partner: {
    name: "Onsective Inc.",
    description:
      "It's Not Techy is the official marketing partner of Onsective Inc., a global IT consultancy delivering enterprise engineering, cloud, AI, and digital transformation.",
    website: "https://onsective.com",
    role: "Parent IT consultancy",
  },
  offices: [
    { city: "Toronto", country: "Canada", flag: "🇨🇦", role: "Global HQ", tz: "America/Toronto" },
    { city: "New York", country: "USA", flag: "🇺🇸", role: "Americas Hub", tz: "America/New_York" },
    { city: "London", country: "United Kingdom", flag: "🇬🇧", role: "EMEA Hub", tz: "Europe/London" },
    { city: "Dubai", country: "UAE", flag: "🇦🇪", role: "Middle East Hub", tz: "Asia/Dubai" },
    { city: "Mumbai", country: "India", flag: "🇮🇳", role: "APAC Delivery Center", tz: "Asia/Kolkata" },
    { city: "Singapore", country: "Singapore", flag: "🇸🇬", role: "APAC Hub", tz: "Asia/Singapore" },
    { city: "Sydney", country: "Australia", flag: "🇦🇺", role: "Oceania Hub", tz: "Australia/Sydney" },
    { city: "Berlin", country: "Germany", flag: "🇩🇪", role: "EU Engineering", tz: "Europe/Berlin" },
  ],
  coreServices: [
    { key: "web-development", label: "Web Design" },
    { key: "seo", label: "SEO" },
    { key: "social-media-marketing", label: "Social Media" },
    { key: "video-production", label: "Video Production" },
    { key: "branding", label: "Brand Design" },
    { key: "social-media-strategy", label: "Social Media Strategy" },
    { key: "performance-marketing", label: "Paid Marketing" },
    { key: "marketing-platforms", label: "Marketing Platforms" },
  ],
  socials: {
    instagram: "https://www.instagram.com/itsnottechy/",
    facebook: "https://www.facebook.com/profile.php?id=61572010214066",
    linkedin: "https://www.linkedin.com/company/itsnottechy/",
    google: "https://share.google/VOwrtSgYzAJzLujrG",
  },
  founded: "2024",
  colors: {
    brand: "#00b3a4",
    ink: "#1C1F26",
    white: "#ffffff",
  },
  keywords: [
    "digital marketing agency",
    "It's Not Techy",
    "itsnottechy",
    "Onsective",
    "Onsective Inc",
    "Onsective partner",
    "Toronto digital marketing agency",
    "Canada marketing agency",
    "custom website development",
    "web design Toronto",
    "web design agency",
    "SEO agency",
    "SEO Toronto",
    "performance marketing",
    "paid marketing",
    "paid media agency",
    "social media marketing",
    "social media strategy",
    "video production agency",
    "brand design",
    "branding agency",
    "marketing platforms",
    "Google Ads management",
    "Meta Ads agency",
    "content marketing",
    "email marketing",
    "marketing automation",
    "AI marketing",
    "lead generation",
    "ecommerce marketing",
    "Shopify marketing",
    "WordPress development",
    "Next.js development",
    "conversion rate optimization",
    "growth marketing",
    "influencer marketing",
    "LinkedIn marketing",
    "YouTube marketing",
    "TikTok marketing",
    "Instagram marketing",
    "local SEO",
    "technical SEO",
    "link building",
    "online reputation management",
    "Etobicoke marketing agency",
    "GTA digital agency",
    "New York marketing agency",
    "London marketing agency",
    "Dubai marketing agency",
    "Mumbai marketing agency",
    "Singapore marketing agency",
    "Sydney marketing agency",
    "Berlin marketing agency",
  ],
};
